# prometheus.yml
global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.

storage:
  tsdb:
    # A 10min time window is enough because it can easily absorb retries and network delays.
    out_of_order_time_window: 10m
